# Form implementation generated from reading ui file 'designs/12345.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(800, 600)
		self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.label = QtWidgets.QLabel(parent=self.centralwidget)
		self.label.setGeometry(QtCore.QRect(90, 50, 591, 371))
		self.label.setText("")
		self.label.setTextFormat(QtCore.Qt.TextFormat.RichText)
		self.label.setPixmap(QtGui.QPixmap(":/Mnemoscheme/тб.svg"))
		self.label.setScaledContents(True)
		self.label.setObjectName("label")
		self.radioButton = QtWidgets.QRadioButton(parent=self.centralwidget)
		self.radioButton.setGeometry(QtCore.QRect(330, 430, 20, 21))
		self.radioButton.setStyleSheet("QRadioButton\n"
"{\n"
"	color: red;\n"
"}\n"
"QRadioButton:indicator:checked\n"
"{\n"
"	image: url(:/Mnemoscheme/greenlamp.svg);\n"
"	width: 15px;\n"
"	height: 15px;\n"
"}\n"
"QRadioButton:indicator:unchecked\n"
"{\n"
"	image: url(:/Mnemoscheme/redlamp.svg);\n"
"	width: 15px;\n"
"	height: 15px;\n"
"}\n"
"")
		self.radioButton.setText("")
		self.radioButton.setIconSize(QtCore.QSize(50, 50))
		self.radioButton.setCheckable(False)
		self.radioButton.setChecked(False)
		self.radioButton.setObjectName("radioButton")
		MainWindow.setCentralWidget(self.centralwidget)
		self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
		self.menubar.setObjectName("menubar")
		MainWindow.setMenuBar(self.menubar)
		self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
		self.statusbar.setObjectName("statusbar")
		MainWindow.setStatusBar(self.statusbar)

		self.retranslateUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
