# Form implementation generated from reading ui file '.\designs\addTankDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddTankDialog(object):
    def setupUi(self, AddTankDialog):
        AddTankDialog.setObjectName("AddTankDialog")
        AddTankDialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=AddTankDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(AddTankDialog)
        self.buttonBox.accepted.connect(AddTankDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(AddTankDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AddTankDialog)

    def retranslateUi(self, AddTankDialog):
        _translate = QtCore.QCoreApplication.translate
        AddTankDialog.setWindowTitle(_translate("AddTankDialog", "Dialog"))
