# Form implementation generated from reading ui file 'designs/addTankDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddTankDialog(object):
	def setupUi(self, AddTankDialog):
		AddTankDialog.setObjectName("AddTankDialog")
		AddTankDialog.resize(400, 300)
		self.buttonBox = QtWidgets.QDialogButtonBox(parent=AddTankDialog)
		self.buttonBox.setGeometry(QtCore.QRect(10, 260, 381, 32))
		self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
		self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Save)
		self.buttonBox.setCenterButtons(False)
		self.buttonBox.setObjectName("buttonBox")
		self.formLayoutWidget = QtWidgets.QWidget(parent=AddTankDialog)
		self.formLayoutWidget.setGeometry(QtCore.QRect(80, 100, 231, 80))
		self.formLayoutWidget.setObjectName("formLayoutWidget")
		self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
		self.formLayout.setLabelAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
		self.formLayout.setFormAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
		self.formLayout.setContentsMargins(0, 0, 0, 0)
		self.formLayout.setObjectName("formLayout")
		self.label = QtWidgets.QLabel(parent=self.formLayoutWidget)
		self.label.setObjectName("label")
		self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
		self.tank_name = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
		self.tank_name.setObjectName("tank_name")
		self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.tank_name)
		self.label_2 = QtWidgets.QLabel(parent=self.formLayoutWidget)
		self.label_2.setObjectName("label_2")
		self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
		self.mqtt_topic = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
		self.mqtt_topic.setObjectName("mqtt_topic")
		self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.mqtt_topic)

		self.retranslateUi(AddTankDialog)
		self.buttonBox.accepted.connect(AddTankDialog.accept) # type: ignore
		self.buttonBox.rejected.connect(AddTankDialog.reject) # type: ignore
		QtCore.QMetaObject.connectSlotsByName(AddTankDialog)

	def retranslateUi(self, AddTankDialog):
		_translate = QtCore.QCoreApplication.translate
		AddTankDialog.setWindowTitle(_translate("AddTankDialog", "Dialog"))
		self.label.setText(_translate("AddTankDialog", "Имя"))
		self.label_2.setText(_translate("AddTankDialog", "Топик MQTT"))
