# Form implementation generated from reading ui file '.\designs\adminPage.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AdminWindow(object):
    def setupUi(self, AdminWindow):
        AdminWindow.setObjectName("AdminWindow")
        AdminWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=AdminWindow)
        self.centralwidget.setObjectName("centralwidget")
        AdminWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=AdminWindow)
        self.statusbar.setObjectName("statusbar")
        AdminWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(parent=AdminWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.sensors = QtWidgets.QMenu(parent=self.menubar)
        self.sensors.setObjectName("sensors")
        self.actuators = QtWidgets.QMenu(parent=self.menubar)
        self.actuators.setAcceptDrops(False)
        self.actuators.setToolTipsVisible(False)
        self.actuators.setObjectName("actuators")
        self.params = QtWidgets.QMenu(parent=self.menubar)
        self.params.setObjectName("params")
        self.users = QtWidgets.QMenu(parent=self.menubar)
        self.users.setObjectName("users")
        self.tanks = QtWidgets.QMenu(parent=self.menubar)
        self.tanks.setAcceptDrops(True)
        self.tanks.setObjectName("tanks")
        AdminWindow.setMenuBar(self.menubar)
        self.add_tank = QtGui.QAction(parent=AdminWindow)
        self.add_tank.setObjectName("add_tank")
        self.add_sensor = QtGui.QAction(parent=AdminWindow)
        self.add_sensor.setObjectName("add_sensor")
        self.add_actuator = QtGui.QAction(parent=AdminWindow)
        self.add_actuator.setObjectName("add_actuator")
        self.add_param = QtGui.QAction(parent=AdminWindow)
        self.add_param.setObjectName("add_param")
        self.add_user = QtGui.QAction(parent=AdminWindow)
        self.add_user.setCheckable(True)
        self.add_user.setObjectName("add_user")
        self.sensors.addAction(self.add_sensor)
        self.actuators.addAction(self.add_actuator)
        self.params.addAction(self.add_param)
        self.users.addAction(self.add_user)
        self.tanks.addAction(self.add_tank)
        self.menubar.addAction(self.tanks.menuAction())
        self.menubar.addAction(self.sensors.menuAction())
        self.menubar.addAction(self.actuators.menuAction())
        self.menubar.addAction(self.params.menuAction())
        self.menubar.addAction(self.users.menuAction())

        self.retranslateUi(AdminWindow)
        QtCore.QMetaObject.connectSlotsByName(AdminWindow)

    def retranslateUi(self, AdminWindow):
        _translate = QtCore.QCoreApplication.translate
        AdminWindow.setWindowTitle(_translate("AdminWindow", "MainWindow"))
        self.sensors.setTitle(_translate("AdminWindow", "Датчики"))
        self.actuators.setTitle(_translate("AdminWindow", "Актуаторы"))
        self.params.setTitle(_translate("AdminWindow", "Параметры"))
        self.users.setTitle(_translate("AdminWindow", "Пользователи"))
        self.tanks.setTitle(_translate("AdminWindow", "Емкости"))
        self.add_tank.setText(_translate("AdminWindow", "Добавить"))
        self.add_sensor.setText(_translate("AdminWindow", "Добавить"))
        self.add_actuator.setText(_translate("AdminWindow", "Добавить"))
        self.add_param.setText(_translate("AdminWindow", "Добавить"))
        self.add_user.setText(_translate("AdminWindow", "Добавить"))
