# Form implementation generated from reading ui file 'designs/design.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(800, 600)
		self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.formLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
		self.formLayoutWidget.setGeometry(QtCore.QRect(230, 210, 251, 131))
		self.formLayoutWidget.setObjectName("formLayoutWidget")
		self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
		self.formLayout.setContentsMargins(0, 0, 0, 0)
		self.formLayout.setObjectName("formLayout")
		self.label = QtWidgets.QLabel(parent=self.formLayoutWidget)
		self.label.setObjectName("label")
		self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
		self.login = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
		self.login.setText("")
		self.login.setObjectName("login")
		self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.login)
		self.label_2 = QtWidgets.QLabel(parent=self.formLayoutWidget)
		self.label_2.setObjectName("label_2")
		self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
		self.passwd = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
		self.passwd.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDate|QtCore.Qt.InputMethodHint.ImhHiddenText|QtCore.Qt.InputMethodHint.ImhNoAutoUppercase|QtCore.Qt.InputMethodHint.ImhNoPredictiveText|QtCore.Qt.InputMethodHint.ImhPreferLowercase|QtCore.Qt.InputMethodHint.ImhSensitiveData|QtCore.Qt.InputMethodHint.ImhUppercaseOnly)
		self.passwd.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
		self.passwd.setObjectName("passwd")
		self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.passwd)
		self.log_in_button = QtWidgets.QPushButton(parent=self.formLayoutWidget)
		self.log_in_button.setObjectName("log_in_button")
		self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.log_in_button)
		MainWindow.setCentralWidget(self.centralwidget)
		self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
		self.menubar.setObjectName("menubar")
		MainWindow.setMenuBar(self.menubar)
		self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
		self.statusbar.setObjectName("statusbar")
		MainWindow.setStatusBar(self.statusbar)

		self.retranslateUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
		self.label.setText(_translate("MainWindow", "Логин"))
		self.label_2.setText(_translate("MainWindow", "Пароль"))
		self.log_in_button.setText(_translate("MainWindow", "Войти"))
