# Form implementation generated from reading ui file 'designs/loginPageDialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ErrorLoginDialog(object):
	def setupUi(self, ErrorLoginDialog):
		ErrorLoginDialog.setObjectName("ErrorLoginDialog")
		ErrorLoginDialog.resize(400, 300)
		self.buttonBox = QtWidgets.QDialogButtonBox(parent=ErrorLoginDialog)
		self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
		self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
		self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close)
		self.buttonBox.setCenterButtons(False)
		self.buttonBox.setObjectName("buttonBox")
		self.verticalLayoutWidget = QtWidgets.QWidget(parent=ErrorLoginDialog)
		self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 90, 286, 80))
		self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
		self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
		self.verticalLayout.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout.setObjectName("verticalLayout")
		self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
		font = QtGui.QFont()
		font.setPointSize(14)
		font.setBold(True)
		self.label.setFont(font)
		self.label.setObjectName("label")
		self.verticalLayout.addWidget(self.label)
		self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.label_2.setFont(font)
		self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
		self.label_2.setObjectName("label_2")
		self.verticalLayout.addWidget(self.label_2)

		self.retranslateUi(ErrorLoginDialog)
		self.buttonBox.accepted.connect(ErrorLoginDialog.accept) # type: ignore
		self.buttonBox.rejected.connect(ErrorLoginDialog.reject) # type: ignore
		QtCore.QMetaObject.connectSlotsByName(ErrorLoginDialog)

	def retranslateUi(self, ErrorLoginDialog):
		_translate = QtCore.QCoreApplication.translate
		ErrorLoginDialog.setWindowTitle(_translate("ErrorLoginDialog", "Неправильные данные"))
		self.label.setText(_translate("ErrorLoginDialog", "Неправильный логин/пароль "))
		self.label_2.setText(_translate("ErrorLoginDialog", "Попробуйте еще раз"))
