# Form implementation generated from reading ui file 'designs/operatorPage.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OperatorWindow(object):
	def setupUi(self, OperatorWindow):
		OperatorWindow.setObjectName("OperatorWindow")
		OperatorWindow.resize(800, 600)
		self.centralwidget = QtWidgets.QWidget(parent=OperatorWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
		self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 30, 231, 80))
		self.gridLayoutWidget.setObjectName("gridLayoutWidget")
		self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
		self.gridLayout.setContentsMargins(0, 0, 0, 0)
		self.gridLayout.setObjectName("gridLayout")
		self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
		self.label_3.setObjectName("label_3")
		self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
		self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
		self.label_2.setObjectName("label_2")
		self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
		self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
		self.label.setObjectName("label")
		self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
		self.curr_process = QtWidgets.QLabel(parent=self.gridLayoutWidget)
		self.curr_process.setObjectName("curr_process")
		self.gridLayout.addWidget(self.curr_process, 1, 1, 1, 1)
		self.next_process = QtWidgets.QLabel(parent=self.gridLayoutWidget)
		self.next_process.setObjectName("next_process")
		self.gridLayout.addWidget(self.next_process, 2, 1, 1, 1)
		self.tank_selector = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
		self.tank_selector.setObjectName("tank_selector")
		self.gridLayout.addWidget(self.tank_selector, 0, 1, 1, 1)
		self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
		self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 409, 791, 171))
		self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
		self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
		self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
		self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.graph = PlotWidget(parent=self.horizontalLayoutWidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.graph.sizePolicy().hasHeightForWidth())
		self.graph.setSizePolicy(sizePolicy)
		self.graph.setObjectName("graph")
		self.horizontalLayout.addWidget(self.graph)
		OperatorWindow.setCentralWidget(self.centralwidget)
		self.statusbar = QtWidgets.QStatusBar(parent=OperatorWindow)
		self.statusbar.setObjectName("statusbar")
		OperatorWindow.setStatusBar(self.statusbar)

		self.retranslateUi(OperatorWindow)
		QtCore.QMetaObject.connectSlotsByName(OperatorWindow)

	def retranslateUi(self, OperatorWindow):
		_translate = QtCore.QCoreApplication.translate
		OperatorWindow.setWindowTitle(_translate("OperatorWindow", "MainWindow"))
		self.label_3.setText(_translate("OperatorWindow", "Следующий процесс"))
		self.label_2.setText(_translate("OperatorWindow", "Текущий процесс"))
		self.label.setText(_translate("OperatorWindow", "Ёмкость"))
		self.curr_process.setText(_translate("OperatorWindow", "TextLabel"))
		self.next_process.setText(_translate("OperatorWindow", "TextLabel"))
from pyqtgraph import PlotWidget
